# A scrape configuration scraping a Node Exporter and the Prometheus server
# itself.
scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:9090
- job_name: push-gateway
  scrape_interval: 5s
  static_configs:
  - targets:
    - push:9091
- job_name: metrics
  scrape_interval: 5s
  static_configs:
  - targets:
    - grafana:3000
